/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ManateeSeedMigrations {
  version: string;
}

export interface ManateeUsers {
  created_at: Generated<Timestamp>;
  email: string;
  firstname: string;
  id: Generated<number>;
  lastname: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ManateexUsers {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface ManateUsers {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface ManatexcdxUsers {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface ManatexcUsers {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface ManatexUsers {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  username: string;
}

export interface DB {
  "manate.users": ManateUsers;
  "manatee.seed_migrations": ManateeSeedMigrations;
  "manatee.users": ManateeUsers;
  "manateex.users": ManateexUsers;
  "manatex.users": ManatexUsers;
  "manatexc.users": ManatexcUsers;
  "manatexcdx.users": ManatexcdxUsers;
  users: Users;
}
